### ISSUE TITLE
Newbie question - MacOS

### ISSUE THREAD

**Issue by pevans01** [jameschch/LeanParameterOptimization#12]
Hi James,

This is probably the wrong place to ask, I apologise.  I think what you're developing here is super cool.

I'm a complete noob, this is the first C# project I've ever built.  How far am I going to be able to get with this on MacOS, or rather, am I going to be able to optimise parameters for my QC algos while using MacOS?

I was able to build and run the Blazor app but not the legacy launcher.

Thanks

**Comment by jameschch** [comment]
It's very encouraging that you took the time to look at the optimizer project.

If you are looking for general help, it's better if you try the [gitter chat](https://gitter.im/LeanParameterOptimization/community).

**Comment by pevans01** [comment]
Thanks James, I've reached out for help on there.
