### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by IlshatGaripov** [jameschch/LeanParameterOptimization#14]
@jameschch  please take a look I have got idea. This is an optimization engine working along with WPF lean-monitor client https://github.com/mirthestam/lean-monitor. I put it together. In result things looks similiar to this
![image](https://user-images.githubusercontent.com/37403501/95342907-974bc380-08c0-11eb-9fe5-ba107400b115.png)
on the left there is menu with items representing optimization parameters - by clicking on each item - a graph will be displayed with all trades stats performance charts corresponding to these parameters. Can you use code in WPF in your application?

**Comment by jameschch** [comment]
I expect all of the data needed for this kind of chart can be collected from my Optimizer. I tend to need to visualize a large number of optimization runs and so have a charting app for this:

[Example](https://raw.githubusercontent.com/jameschch/LeanParameterOptimization/master/chart.png
)

[https://optimizers.ml/chart](https://optimizers.ml/Chart)
