### ISSUE TITLE
Features on the Blazer App not working

### ISSUE THREAD

**Issue by tonymds** [jameschch/LeanParameterOptimization#2]
Hello, first of all, let me congratulate you for the great and creative work you have done here :)

I am getting some issues with the Blazzor app, none of the features of the Config page work (load sample, upload, changing values). The repo is a fresh clone with no changes.

Here's a screenshot of one of the issues, but I have others (null reference on the model, etc)
![2020-03-04 18_38_36-↝Algorithm Optimization↝](https://user-images.githubusercontent.com/9167919/75911960-4fefe700-5e48-11ea-9595-d1ca35a50e52.png)

I've tried to fix this but my knowledge on Blazzor is short since it's so recent and the debugger is really limited. If you have any time you can try to check this out, otherwise I will probably export the data to csv or something to plot the results.

**Comment by jameschch** [comment]
So pleased you think the effort is worthwhile. I'm sure you're aware this is a WIP pre-release. That said, most things work, but might look unpolished. No docs yet - sorry about that.

Everything runs in the browser. Even file upload and forms input never needs to go to the server. Welcome to Blazorland.

[http://optimizer.ml/config](http://optimizer.ml/config)
The config editor

[http://optimizer.ml/config](http://optimizer.ml/chart)
Can ingest your optimizer.txt results file and visualize with plotly.

[http://optimizer.ml/config](http://optimizer.ml/codeeditor)
An C#/Javascript code editor to test the optimizer config and run optimization multi-threaded in the browser (the C# compile is on server). Toying around with grid search can produce some satisfying charts.

**Comment by jameschch** [comment]
The blazor reference has since updated. I'm not aware of specific issues that might cause your problem. I can help with your environment setup in the gitter: 
https://gitter.im/LeanParameterOptimization/community

**Comment by tonymds** [comment]
Thank you James, I will get back to this when I have the time, I'm sure it's easy to fix.
