### ISSUE TITLE
BacktestingResultHandler class does not have a Run method to invoke

### ISSUE THREAD

**Issue by captholley** [jameschch/LeanParameterOptimization#6]
I have been able to successfully build and deploy the Blazor app. I have followed the directions of the ReadMe to edit the configuration file first. When I deploy the app, are there specific steps I need to take to get the application running? Loading the configuration file from the configuration tab does not seem to work.

I have also tried running the Legacy Program and it keeps getting hung up at the Run() method, stating that the BacktestingResultHandler class does not have a Run method to invoke. Checking the QuantConnect code this is wrong as the Run method does in fact exist. What am I doing wrong here?

**Comment by jameschch** [comment]
If you just want to optimize parameters, then you need to configure and run the project Jtc.Optimization.Launcher.Legacy. It's worth checking that your local Lean source is up to date. Do you want to include the relevant errors from log.txt and error.txt?

The blazor app at the moment just has some supporting tools that are hosted here; [https://optimizer.ml](https://optimizer.ml).
