### ISSUE TITLE
Failed to complete setup of assembly (hr = 0x8007000b)

### ISSUE THREAD

**Issue by abhi555shek** [jameschch/LeanParameterOptimization#7]
Hi,

I have followed all the steps given and I am running this package on same parent as Lean but getting the following error. Could you please indicate what this could mean?

LOG: Attempting download of new URL file:///C:/Users/Abhishek/Source/Repos/LeanParameterOptimization/Jtc.Optimization.Launcher.Legacy/bin/Debug/QuantConnect.Lean.Engine.DLL.
ERR: Failed to complete setup of assembly (hr = 0x8007000b). Probing terminated.

2020-06-16 18:33:50.0165 System.BadImageFormatException: Could not load file or assembly 'QuantConnect.Lean.Engine, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.

**Comment by jameschch** [comment]
Did you build both Lean and the optimizer dll's using x86 or x64? Mixing the two would result in bad format exception.

**Comment by abhi555shek** [comment]
Thanks James
