### ISSUE TITLE
Unable to run the optimizer

### ISSUE THREAD

**Issue by rmadgula** [jameschch/LeanParameterOptimization#9]
I have been trying to run the optimizer - but it continuously gives me this runtime error. I have Lean and the optimizer sitting in the same folder. Also the log files look clean and dont give out any information. I have attached the details of the error that shows. Everything builds fine but when you run it throws an error. Please please help. 
![image](https://user-images.githubusercontent.com/67287317/86838711-82b42100-c06e-11ea-8307-3131adb85c85.png)

**Comment by rmadgula** [comment]
I have used your forked version of lean and your latest code of optimizer

**Comment by jameschch** [comment]
I have tracked this down to an odd problem with binding redirects. Should be fixed in current master branch.
